repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
  - repo: https://github.com/ambv/black
    rev: "24.1.1"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.3.0"
    hooks:
      - id: pydocstyle
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.2.1"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
  - repo: https://github.com/markdownlint/markdownlint
    rev: "v0.12.0"
    hooks:
      - id: markdownlint

ci:
  skip: [poetry-lock]
