version: "3"

services:
  streamlit:
    image: ghcr.io/kasiafoszcz/amorphousmetals:${DOCKER_TAG:-edge}
    build: .
    ports:
      - 8501:8501
    volumes:
      - cache:/app/.streamlit/cache

  streamlit-local:
    image: ghcr.io/kasiafoszcz/amorphousmetals:${DOCKER_TAG:-edge}
    build: .
    ports:
      - 8501:8501
    volumes:
      - ./amorphous_metals:/app/amorphous_metals:ro
      - ./data:/app/data:ro
      - cache:/app/.streamlit/cache
    environment:
      STREAMLIT_SERVER_RUN_ON_SAVE: True

volumes:
  cache:
